local MSQ = LibStub('Masque', true)
if not MSQ then return end

MSQ:AddSkin('Hxcktivist - rectangle', {
	Author = 'Hxcktivist',
	Version = string.match(GetAddOnMetadata('Masque_Hxcktivist', 'Version'), '%d+'),
	Masque_Version = 90001,
	Shape = 'rectangle',
	Description = "A simple rectangle pixel border skin.",

	Backdrop = {
		Width = 30,
		Height = 17,
		Color = {0, 0, 0, 0.75},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\No_Backdrop]],
	},
	Icon = {
		Width = 29,
		Height = 17,
		TexCoords = {0.07,0.93,0.28,0.8},
	},
	Flash = {
		Width = 30,
		Height = 18,
		Color = {1, 1, 1, 0.5},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Flash]],
	},
	Cooldown = {
		Width = 27,
		Height = 14,
		Color = {0, 0, 0, 0.75},
	},
	Pushed = {
		Width = 27,
		Height = 14,
		Color = {0, 204/255, 1, 0.4},
		BlendMode = 'BLEND',
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Pushed]],
	},
	Normal = {
		Width = 30,
		Height = 18,
		Color = {0, 0, 0, 1},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Normal]],
	},
	Checked = {
		Width = 30,
		Height = 18,
		BlendMode = 'ADD',
		Color = {1, 204/255, 0, 0.4},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Checked]],
	},
	Border = {
		Width = 30,
		Height = 18,
		BlendMode = "ADD",
		DrawLayer = "OVERLAY",
		DrawLevel = 5,
		Color = {1, 1, 1, 1},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Border]],
	},
	Gloss = {
		Width = 30,
		Height = 18,
		BlendMode = 'ADD',
		Color = {1, 1, 1, 0.6},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Gloss]],
	},
	AutoCastable = {
		Width = 30,
		Height = 18,
		OffsetX = 0.5,
		OffsetY = -0.5,
		Texture = [[Interface\Buttons\UI-AutoCastableOverlay]],
	},
	Highlight = {
		Width = 30,
		Height = 18,
		BlendMode = 'ADD',
		Color = {1, 1, 1, 1},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Highlight]],
	},
	SpellHighlight = {
		Width = 30,
		Height = 18,
		BlendMode = 'BLEND',
		Color = {1, 204/255, 0, 1},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Highlight]],
	},
	NewAction = {
		Width = 30,
		Height = 18,
		BlendMode = 'BLEND',
		Color = {1, 204/255, 0, 1},
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Highlight]],
	},
	NewItem = {
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Border]],
		Color = {1, 1, 1, 1},
		BlendMode = "ADD",
		DrawLayer = "OVERLAY",
		DrawLevel = 2,
		Width = 36,
		Height = 36,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 0,
		OffsetY = 0,
	},
	Name = {
		JustifyH = "LEFT",
		JustifyV = "TOP",
		Width = 28,
		Height = 10,
		DrawLayer = "OVERLAY",
		DrawLevel = 10,
		Point = "TOPLEFT",
		RelPoint = "TOPLEFT",
		OffsetX = 0.5,
		OffsetY = -1,
	},
	Count = {
		JustifyH = "RIGHT",
		JustifyV = "BOTTOM",
		Width = 30,
		Height = 10,
		DrawLayer = "OVERLAY",
		DrawLevel = 10,
		Point = "BOTTOMRIGHT",
		RelPoint = "BOTTOMRIGHT",
		OffsetX = 1,
		OffsetY = 1,
	},
	HotKey = {
		JustifyH = "RIGHT",
		JustifyV = "TOP",
		Width = 30,
		Height = 10,
		DrawLayer = "OVERLAY",
		DrawLevel = 10,
		Point = "TOPRIGHT",
		RelPoint = "TOPRIGHT",
		OffsetX = 0.5,
		OffsetY = -1,
	},
	Duration = {
		JustifyH = "CENTER",
		JustifyV = "MIDDLE",
		Width = 36,
		Height = 10,
		Point = "TOP",
		RelPoint = "BOTTOM",
		OffsetX = 0,
		OffsetY = -2,
	},
	AutoCastShine = {
		Width = 34,
		Height = 34,
		OffsetX = 1,
		OffsetY = -1,
	},
	IconBorder = {
		Texture = [[Interface\AddOns\Masque_Hxcktivist\Textures\Border]],
		Color = {0, 0, 0, 0.5},
		Width = 30,
		Height = 17,
		BlendMode = "ADD",
		DrawLayer = "BACKGROUND",
		DrawLevel = 0,
		Point = "CENTER",
		RelPoint = "CENTER",
		OffsetX = 50000000,
		OffsetY = 0,
	},
	UpgradeIcon = {
		Atlas = "bags-greenarrow",
		BlendMode = "BLEND",
		DrawLayer = "OVERLAY",
		DrawLevel = 2,
		Width = 15,
		Height = 16,
		Point = "TOPLEFT",
		RelPoint = "TOPLEFT",
		OffsetX = 3,
		OffsetY = -4,
	},
	JunkIcon = {
		Atlas = "bags-junkcoin",
		BlendMode = "BLEND",
		DrawLayer = "OVERLAY",
		DrawLevel = 5,
		Width = 16,
		Height = 16,
		Point = "TOP",
		RelPoint = "TOP",
		OffsetX = 0,
		OffsetY = 1,
	},
}, true)